version: 2

machine: true

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Bintray
      - publish:
          context: Bintray
          requires:
            - build
          filters:
            branches:
              only:
                - master

  nightly:
    triggers:
      - schedule:
          cron: "14 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: Bintray

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-sid-node
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: futbolin-{{ .Branch }}-{{ checksum "pom.xml" }}

      - run:
          name: Download dependencies and plugins
          command: mvn dependency:go-offline -P coverage -P docker
      - save_cache:
          paths:
            - ~/.m2
          key: futbolin-{{ .Branch }}-{{ checksum "pom.xml" }}

      - run:
          name: Build software
          command: |
            mvn -P coverage \
              clean verify sonar:sonar \
              -Dsonar.projectKey=mthmulders_futbolin \
              -Dsonar.organization=mthmulders-github \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.java.source=11 \
              -Dsonar.login=$SONAR_LOGIN
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - save_cache:
          paths:
            - ~/.m2
            - ~/.sonar/cache
          key: futbolin-{{ .Branch }}-{{ checksum "pom.xml" }}
      - store_test_results:
          path: ~/junit

  publish:
    docker:
      - image: circleci/openjdk:11-jdk-sid-node
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: futbolin-{{ .Branch }}-{{ checksum "pom.xml" }}

      - run:
          name: Publish containers
          command: |
            docker login -u mthmulders -p ${BINTRAY_API_KEY} mthmulders-docker-futbolin.bintray.io
            mvn versions:set -DremoveSnapshot=true
            mvn package dockerfile:push -P docker --pl webapp/
